### ISSUE TITLE
Enhance Readability of input fields in Dark Mode

### ISSUE THREAD

**Issue by Moatassem5** [skytells-research/optimal-training-calculator#1]
### In the Dark Mode the contrast between background color and font color in all input fields is very poor
![image](https://github.com/user-attachments/assets/ec019701-094f-4562-acc4-d7d8733ea69d)

- **I think this issue is a result of generalizing the foreground color of the page in Dark Mode preference**
`@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}`

- **I suggest separating the foreground color of the input fields with darker color like `#383838`**

**Comment by DrHazemAli** [comment]
Thank you for bringing this to my attention! 
This will be addressed in the upcoming build. 
Alternatively, if you’d like to contribute, feel free to open a pull request, and l'll review it promptly.
