### ISSUE TITLE
inquiry regrading calculations

### ISSUE THREAD

**Issue by dazmashaly** [skytells-research/optimal-training-calculator#3]
When using local training, how does the system determine the appropriate parameters without considering information about my local GPU? Additionally, how does it calculate the batch size without accounting for the image sizes? For example, the 1v100 GPU option doesn't have enough memory to support a batch size of 1000, as it suggests. Thank you.

**Comment by DrHazemAli** [comment]
Thanks for bringing this up—it’s a really good question, and I totally get where you’re coming from. 
We actually tackled this in the latest version, v1.0.1.


In this update, I added a way for the system to better adapt to local GPU setups. Now, when you choose local training, there’s an option to input your GPU memory under the advanced settings. This lets the calculator make more realistic suggestions based on the specific memory of your GPU, so it doesn’t just throw out huge batch sizes that wouldn’t fit (like the batch size of 1000 on a 1v100—you’re absolutely right, that wouldn’t work).

Also, with the new Advanced Mode, you can set image dimensions (width, height, channels) manually, which helps the calculator gauge a more appropriate batch size that actually fits your GPU. And to make it even clearer, I added color-coded hints that guide you along the way. So, if the batch size or image parameters are too intense for the memory you have, you’ll get a heads-up in the form of a warning or recommendation.

See the `changelog` file for more details about this.

Hopefully, this update makes things a lot smoother when configuring for local hardware. Appreciate your feedback—it’s what helped us make these improvements! Let me know if you have any more thoughts or if something still doesn’t add up. 

Thanks again!
